accounts/urls.py
from django.urls import path
from . import views

app_name = 'AppAccountsName'

urlpatterns = [
    path('signup', views.signup_view, name="PathSignupName"),
    path('login', views.login_view, name='PathLoginName'),
    path('logout', views.logout_view, name='PathLogoutName'),
]

articles/urls.py
from django.contrib import admin
from django.urls import path

from django.urls import path
from . import views

app_name = 'AppArticlesName'
urlpatterns = [
    # path('about/', views.about),
    path('', views.articles_list, name="PathlistName"),
    path('create', views.articles_create, name="PathCreateName"),
    path('<ParamSlug>', views.articles_detail, name="PathDetailName"),

]

djangoproject1/urls.py
from django.contrib import admin
from django.urls import path

from django.contrib import admin
from django.urls import path, include
from . import views
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

# import for media
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import logout
from articles.views import articles_list

# import for media

app_name = 'AppProjectName'

urlpatterns = [
    path('admin/', admin.site.urls),
    path('about/', views.about),
    path('articles/', include('articles.urls')),
    path('accounts/', include('accounts.urls')),
    path('', articles_list),
]

# for static files
urlpatterns += staticfiles_urlpatterns()

# for media file
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/models.py
from django.db import models

# Create your models here.

articles/models.py
import datetime

from django.db import models
from django.contrib.auth.models import User


# Create your models here.
class article(models.Model):
    title = models.CharField(max_length=150)
    slug = models.SlugField()
    body = models.TextField()
    date = models.DateField(auto_now_add=True)
    image = models.ImageField(default='defaultimage.jpg', blank=True)
    author = models.ForeignKey(User, default=None, on_delete=models.CASCADE)
    datarticle = models.DateField(default=datetime.date.today())

    def __str__(self):
        return self.title

    def snippet(self):
        return self.body[0:50] + '...'

todoplanning/models.py
from django.db import models


class TodoItem(models.Model):
    des_work_todoitem = models.CharField(max_length=100)
    flg_checked_todoitem = models.BooleanField(default=False)
    dat_do_todoitem = models.DateField()
    dat_planning_todoitem = models.DateTimeField(auto_now=True)


    def __str__(self):
         return self.des_work_todoitem

articles/forms.py
from django import forms
from . import models


class createarticle(forms.ModelForm):
    class Meta:
        model = models.article
        fields = ['title', 'slug', 'body', 'image','datarticle']

accounts/views.py
from django.shortcuts import render, redirect, HttpResponse
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth import login, logout
from django.contrib.auth.models import User
from django.contrib import auth


def signup_view(request):
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            Varuser = form.save()
            login(request, Varuser)
            return redirect('AppArticlesName:PathlistName')
            # return redirect('AppAccountsName:PathLoginName')

    else:
        form = UserCreationForm()

    return render(request, '../templates/signup.html', {'form': form})


def login_view(request):
    if request.method == 'POST':
        form = AuthenticationForm(data=request.POST)
        if form.is_valid():
            Varuser = form.get_user()
            login(request, Varuser)
            if 'VarNextPage' in request.POST:
                return redirect(request.POST.get('VarNextPage'))
            else:
                return redirect('AppArticlesName:PathlistName')
    else:
        form = AuthenticationForm()

    return render(request, '../templates/login.html', {'form': form})
    # return render(request, "{% url 'AppAccountsName:PathLoginName' %}", {form: form})


def logout_view(request):
    if request.method == 'POST':
        logout(request)
        return redirect('AppArticlesName:PathlistName')
        # return  redirect('AppProjectName:PathHomeName')

articles/views.py
from django.shortcuts import render, HttpResponse, redirect
from . import models
from django.contrib.auth.decorators import login_required
from . import forms


def articles_list(request):
    varArticlesObject = models.article.objects.all().order_by('-date')
    varArticleList = {'VarTableArticle': varArticlesObject}
    return render(request, '../templates/articlelist.html', varArticleList)


def articles_detail(request, ParamSlug):
    varArticlesObject = models.article.objects.get(slug=ParamSlug)
    # varArticleList  = {'VarTableArticle': varArticlesObject}
    return render(request, '../templates/articledetail.html', {'VarTableArticle': varArticlesObject})


@login_required(login_url='/accounts/login')
def articles_create(request):
    if request.method == 'POST':
        VarForm = forms.createarticle(request.POST, request.FILES)
        if VarForm.is_valid():
            # save article
            Varinstance = VarForm.save(commit=False)
            Varinstance.author = request.user
            Varinstance.save()
            return redirect('AppArticlesName:PathlistName')
    else:
        VarForm = forms.createarticle()

    return render(request, '../templates/articlecreate.html', {'ArticleForm': VarForm})

djangoproject1/views.py
from django.shortcuts import render
from django.shortcuts import HttpResponse

def about(request) :
    # return  HttpResponse('Hi , hello world')
     return render(request,'about.html')


def home(request):
    # return  HttpResponse('hi home')
    return  render(request,'home.html')

accounts/templates/login.html
{% extends 'base.html' %}

{% block content %}
    <h1>Login</h1>
    {#    <form class="" action="login.html" method="post">#}
    <form class="" action="{% url 'AppAccountsName:PathLoginName' %}" method="post">
        {{ form }}
        {% csrf_token %}
        {% if request.GET.next %}
            <input type="hidden" name="VarNextPage" value="{{ request.GET.next }}">
        {% endif %}
        <input type="submit" , value="Login">
    </form>

{% endblock %}

accounts/templates/signup.html
{% extends 'base.html' %}

{% block content %}

    <h1> Singup </h1>
    {#  <form class='site-form' action="/accounts/signup" method='post'>#}
    <form class = 'site-form' action="{% url 'AppAccountsName:PathSignupName' %}" method = 'post'>
        {{ form }}
        {% csrf_token %}
        <input type="submit"  value="Signup">
    </form>

{% endblock %}

articles/templates/articlecreate.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

    <div class="create-article">
        <h1>
            create your article!
        </h1>
        <form class='site-form' action="{% url 'AppArticlesName:PathCreateName' %}" method="post"
              enctype="multipart/form-data">
            {{ ArticleForm }}
            {% csrf_token %}
            <input type="submit" name="" value="create">

        </form>
    </div>
    <script src="{% static 'slugify.js' %}"></script>
{% endblock %}

articles/templates/articledetail.html
{% extends 'base.html' %}

{% block content %}
    <div class='article-detail'>
        <div class='article'>
             <img src="{{ VarTableArticle.image.url }}" alt = "" width="500" height="500" align="center">

             <h2>{{ VarTableArticle.title }}</h2>
             <p> {{ VarTableArticle.body }}</p>
             <p> {{ VarTableArticle.slug }}</p>
             <p> {{ VarTableArticle.date}} </p>
{#             <p> {{ VarTableArticle.image}} </p>#}
        </div>
    </div>
{% endblock %}

articles/templates/articlelist.html
{% extends 'base.html' %}

<title>
    {% block title %}
        Title article
    {% endblock %}
</title>

{% block content %}

    <h1>'Article list'</h1>
    <div class="articles">
        {% for perArticle in VarTableArticle %}
            <div class="article">
                <h2><a href="{% url 'AppArticlesName:PathDetailName' perArticle.slug %} "> {{ perArticle.title }}  </a>
                </h2>
                <p>{{ perArticle.title }}</p>
                <p>{{ perArticle.slug }}</p>
                <p>{{ perArticle.snippet }}</p>
                <p>{{ perArticle.date }}</p>
                <p>{{ perArticle.datarticle }}</p>

                <div class="author">
                    added by {{ perArticle.author.username }}
                </div>
            </div>
        {% endfor %}
    </div>

{% endblock %}

templates/about.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>درباره سایت من </title>
</head>
<body>
<h>درباره سایت من</h>
<p>ما ویونا رو خیلی دوست داریم</p>

</body>
</html>

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    {% block title %}
    {% endblock %}
    <link rel="stylesheet" href="{% static 'style.css' %}">
</head>

<body>
<h2><a href="{% url  'AppArticlesName:PathlistName' %}"> logo </a></h2>
<header>
    <nav>
        <ul>

            {% if  user.is_authenticated %}
                <li>

                    <form class="logout-link" action="{% url 'AppAccountsName:PathLogoutName' %}" method="post">

                        {% csrf_token %}
                        <button type="submit">logout</button>
                    </form>

                </li>
                <li>
                    <a class="highlight"   href="{% url 'AppArticlesName:PathCreateName' %}"> create new article </a>

                </li>
            {% else %}
                <li>
                    <a href="{% url 'AppAccountsName:PathLoginName' %}"> login user </a>

                </li>

                <li>

                    <a href="{% url 'AppAccountsName:PathSignupName' %}">signup new user</a>

                </li>

            {% endif %}
        </ul>

    </nav>

</header>

<div class='wrapper'>
    {% block content %}
    {% endblock %}
</div>
</body>

</html>

templates/home.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>سایت تمرین ثبت مقالات Django</title>
</head>
<body>
<h> viona</h>
<p>من ویونا هستم ،  به سایت من خوش آمدید</p>
</body>
</html>